require_relative 'lib/notifier/console_notifier'
require_relative 'lib/notifier/email_notifier'
require_relative 'lib/notifier/email_sender'
require_relative 'lib/project/mock_project'
require_relative 'lib/wip_checker'
